### ISSUE TITLE
Add an <OutboundLink> component

### ISSUE THREAD

**Issue by toolness** [mozilla/react-ga#14]
One of the things I've noticed about `react-ga` is that there don't actually seem to be any dependencies on React! :)

But that can change... With the addition of `outboundLink`, I think that it could be very useful to have an `<OutboundLink>` React component that works just like an `<a>`, but adds an `onClick` handler that prevents the default behavior and uses `outboundLink` to track the link and then redirect the user's browser. This will make it super easy for projects like the teach site to integrate with GA!

If you want, I can contribute a PR for this. Or if you've been itching to write a React component yourself, you can do it too--I recommend looking at react-router's [`Link` component](https://github.com/rackt/react-router/blob/master/modules/components/Link.js) to see how to do a basic "subclassing" of the traditional `<a>`.

**Comment by adamlofting** [comment]
I love this idea.

I'd be interested to write this myself, but if this is useful in teach within the next couple of days, please feel free to contribute the PR. I might not get to this until the end of the week otherwise.

**Comment by toolness** [comment]
It's up to you (or our metrics requirements), really--from a purely technical standpoint, we could soft launch without outbound-link tracking for login and integrate it once you're done with the component, or I could implement it and we could have good metrics for soft launch--assuming that we're planning on soft launching later this week, which I'm not actually sure about...

**Comment by Pomax** [comment]
We have a thing in mozilla/webmaker-core that does something like this, but without the metrics (instead checking whether it needs to link out or cause a java-internal view change), over at https://github.com/mozilla/webmaker-core/blob/develop/src/components/link/link.jsx, which is then used like https://github.com/mozilla/webmaker-core/blob/develop/src/pages/page/page-controls.jsx#L28
