### ISSUE TITLE
Using more than one tracking code

### ISSUE THREAD

**Issue by nicolasiensen** [mozilla/react-ga#26]
Hey,

I want to use react-ga with more than one tracking code.

Is it possible? Should I initialize react-ga again to switch between tracking codes? Can I create multiple instances of react-ga to manage different Google Analytics accounts?

Thanks!

**Comment by mrsln** [comment]
Hi! 

I guess you've done something about it.
Here's a [documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/method-reference#named) about using multiple trackers on a single page.
But it's not possible with the current version of react-ga, because [it doesn't pass options] (https://github.com/mozilla/react-ga/blob/33dec76477c84780fdea9741658a04bed9836082/src/index.js#L109).

**Comment by nicolasiensen** [comment]
That's awesome @mrsln, thank you!

**Comment by reywright** [comment]
I'm assuming I need to access the original ga function in order to support multiple tracking tags here, or is there a cleaner way to do it here.

**Comment by mrsln** [comment]
@reywright I haven't used the library for a long time but I think you can try something like this:
```
ReactGA.initialize('UA-000000-01', {
  gaOptions: {
    name: 'myTracker1',
  },
});

ReactGA.initialize('UA-000000-01', {
  gaOptions: {
    name: 'myTracker2',
  },
});
```

**Comment by RT-TL** [comment]
@reywright I am having the same issue. I wonder how you solved it? Did you use a second instance as @mrsln suggested?

**Comment by reywright** [comment]
I ended up using vanilla GA as I just didn't trust this method, and I needed to use GA on some of our applications non React pages. So I put GA on the same page I mount my React stuff, then I just referenced that in my react components or action files. Eslint complained but I added GA to it so it wouldn't complain anymore.

**Comment by JamesCatt** [comment]
I was able to add a second account by using `ReactGA.ga()` directly:
```javascript
import ReactGA from 'react-ga';
ReactGA.initialize('UA-000000-1');
ReactGA.ga('create', 'UA-000000-2', 'auto', {'name':'myOtherTracker'});
      
const logPageView = () => {
    ReactGA.set({ page: window.location.pathname });
    ReactGA.pageview(window.location.pathname);
    ReactGA.ga('myOtherTracker.send', 'pageview', window.location.pathname);
    return null;
};
```
See https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers for more on creating trackers

See https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#send for more on the `ga.send()` method
